#!/usr/bin/env bash
export GRAFANA_IMAGE=${GRAFANA_IMAGE:="grafana/grafana"}
export GRAFANA_IMAGE_VERSION=${GRAFANA_IMAGE_VERSION:="latest"}
export GRAFANA_ROOT=${GRAFANA_ROOT:="/var/lib/dokku/services/grafana"}
export GRAFANA_HOST_ROOT=${GRAFANA_HOST_ROOT:=$GRAFANA_ROOT}

export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=("backup" "backup-auth" "backup-deauth" "backup-schedule" "backup-schedule-cat" "backup-set-encryption" "backup-unschedule" "backup-unset-encryption" "clone" "connect" "export" "import")
export PLUGIN_COMMAND_PREFIX="chrome"
export PLUGIN_CONFIG_ROOT=${PLUGIN_CONFIG_ROOT:="$DOKKU_LIB_ROOT/config/$PLUGIN_COMMAND_PREFIX"}
export PLUGIN_DATA_ROOT=$GRAFANA_ROOT
export PLUGIN_DATA_HOST_ROOT=$GRAFANA_HOST_ROOT
export PLUGIN_PORTS=(3000)
export PLUGIN_WAIT_PORT=3000
export PLUGIN_DEFAULT_ALIAS="GRAFANA"
export PLUGIN_DISABLE_PULL=${GRAFANA_DISABLE_PULL:=}
export PLUGIN_DISABLE_PULL_VARIABLE="GRAFANA_DISABLE_PULL"
export PLUGIN_ALT_ALIAS="DOKKU_GRAFANA"
export PLUGIN_IMAGE=$GRAFANA_IMAGE
export PLUGIN_IMAGE_VERSION=$GRAFANA_IMAGE_VERSION
export PLUGIN_SCHEME="http"
export PLUGIN_SERVICE="Grafana"
export PLUGIN_VARIABLE="GRAFANA"
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi

if [[ -d "$PLUGIN_DATA_ROOT/*" ]]; then
  rm -rf "${PLUGIN_DATA_ROOT:?}/*"
fi
